- README.md
`xml_root` is not defined. Use other examples to demonstrate the ability of parsing incomplete html document.
> xml_root is not defined

- R/xml_structure.R
- man/xml_structure.Rd
As above. The indent parameter is now actually used when printing indentation for `xml_structure()` when previously it was always using 2 chars.
> Respect the indent parameter when printing xml_structure.

- README.md
The README has code that does not work. Swap function xml out for read_xml.
> Package does not contain xml function

- .travis.yml
- README.md
Use container based travis file with dependency caching and coverage
This will give us much faster builds going forward. To see the coverage
reports we will need to enable them at codecov.io
> Container based travis

- configure
Referencing /bin/bash is not portable and /bin/sh should be used instead. There are no bash-only features used in this script so there should be no problems with the change.
> Changing configure script execution shell for portability.

- configure
Unfortunately we need to explicitly specify bash to work on Solaris.
Reverts hadley/xml2#61
> Revert "Changing configure script execution shell for portability."

- NEWS.md
- R/xml_write.R
- src/xml2_doc.cpp
> Expand paths before passing to libxml2

- R/RcppExports.R
- R/classes.R
- R/utils.R
- src/RcppExports.cpp
- src/xml2_namespace.cpp
This works for printing attributes now, but not for namespaces.
libxml2 doesn't seem to have an exported function to print just attributes, or to print a node _without_ recursively printing its children, which is why I had to do this in R code.
Printing namespaces is going to take a little more work as we don't currently have code to retrieve the namespace for a specific node, just the document as a whole.
Fixes #7
> Print attributes of the root node

- R/RcppExports.R
- src/RcppExports.cpp
- src/xml2_node.cpp
- tests/testthat/test-xml_attrs.R
Fixes #97 
The main issue was for non-element nodes the ns and nsDef structures can be non-null but also invalid as XML_ATTRIBUTE_NODE cannot have its own attributes or namespace definitions. The code assumed they would be NULL but that is clearly not true.
The fix is to only check for attributes if it is an XML_ELEMENT_NODE and return `character()` otherwise.
One other issue this raises is how we want display non-element nodes. Should `format(t1)` be `"c='1'"` or is the previous behavior as `<c>` sufficient. Most of the time I believe people want to work with element nodes, so probably the previous behavior is fine.
> Only look for attributes for element nodes

- src/xml2_node.cpp
- src/xml2_url.cpp
- tests/testthat/test-modify-xml.R
The diff looks bigger than it actually is, the main change in node_attr is assigning to a `xmlChar*` rather than a `const xmlChar*`. The former is freed by `Xml2String()` while the latter is not. xmlNsDefinition should return a `const xmlChar*` as previously as no string is allocated by libxml in that case.
`xmlURIUnescapeString` allocates a string if the target parameter is NULL. This is stated expliictly in the docs but is in the code (See https://github.com/GNOME/libxml2/blob/3eaedba1b64180668fdab7ad2eba549586017bf3/uri.c#L1620-L1627)
Those were all the direct leaks detected, I am still working on the indirect leaks.
Addresses #102
> Fixes for memory leaks found with the LeakSanitizer

- NEWS.md
- R/RcppExports.R
- R/xml_parse.R
- src/RcppExports.cpp
- src/xml2_doc.cpp
- src/xml2_namespace.cpp
- src/xml2_node.cpp
- src/xml2_xpath.cpp
- src/xml_push.cpp
- tests/testthat/test-null.R
This ensures we will generate an error rather than crashing on NULL
XPtrs (as happens when round tripping `saveRDS()/readRDS()`.
Fixes #101
> Use checked_get() in place of get() where possible

- NEWS.md
- R/as_list.R
- man/as_list.Rd
- tests/testthat/test-as.list.R
Fix for issue #115.
With this code, xml `names` attribute will still override the element names if both are specified. That's purely in the interest of maximum consistency with existing behavior, but I think the opposite would be more intuitive (element names win).
> keep element names when xml node has attributes

- R/classes.R
- R/xml_children.R
- tests/testthat/test-null.R
- tests/testthat/test-xml_children.R
This fixes the issue described in #121.
This is mostly achieved by checking whether a document has a root element before attempting to print it.
One other minor bugfix is that an `xml_document` object will now print its children if they were previously absent. An example:
Before:
``` r
> library(xml2)
> doc <- xml_new_document()
> root <- xml_add_child(doc, "root")
> doc
{xml_document}
```
After:
``` r
> library(xml2)
> doc <- xml_new_document()
> root <- xml_add_child(doc, "root")
> doc
{xml_document}
<root>
```
> Allow docs missing a root element to be created and printed. Fixes #121.

- R/xml_text.R
This fixes [#146](https://github.com/hadley/xml2/issues/146). I haven't changed the unit test (mentioned in the issue) but maybe should?.
> Fixed return value in call to vapply in xml_integer.xml_nodeset.

- R/utils.R
- R/xml_attr.R
- tests/testthat/test-xml_attrs.R
This should fix #117. For similar reasons (i.e. working with SVG documents) it would be nice not to have to specify every attribute as a character vector.
Basically this change will cast non-character arguments via `as.character()`.
> Enable non-character attributes to be set.

- .Rbuildignore
- .gitignore
- NEWS.md
- R/RcppExports.R
- R/paths.R
- R/utils.R
- R/xml_parse.R
- R/xml_write.R
- man/write_xml.Rd
- src/RcppExports.cpp
- src/xml2_doc.cpp
- src/xml2_output.cpp
- tests/testthat/test-read-xml.R
- tests/testthat/test-write_xml.R
- tests/testthat/test-xml_missing.R
This provides full connection support for XML and HTML output using the
xmlSave API (http://xmlsoft.org/html/libxml-xmlsave.html). It also
refactors the file output functions to use the xmlSave API as well,
which provides more formatting and encoding options than the previous
APIs.
Closes #157
> Connection support for writing XML and HTML

- NEWS.md
- R/RcppExports.R
- R/xml_modify.R
- src/RcppExports.cpp
- src/xml2_node.cpp
I generate XML documents which can easily have nodes with >10k children. With the current logic in this package, there is no way to add child nodes without iterating through or creating R objects containing the complete list of children.
I restructured xml_add_child so that using `.where=0L` (prepend mode) will bypass these very slow function calls.
With the existing code, using `.where=0L` will produce an error if there are no children, rather than just insert the node as the first and only child. I assume this is a bug so I also included a fix for this in my changes.
> Add child node performance

- DESCRIPTION
- _pkgdown.yml
* Add pkgdown URL to DESCRIPTION
* Add analytics to `_pkgdown.yml`
Having this url in `DESCRIPTION` will allow auto-linking for pkgdown reference pages.
> Add pkgdown URL to DESCRIPTION

- DESCRIPTION
- NEWS.md
- R/xml_find.R
- man/xml_find_all.Rd
- tests/testthat/test-xml_find.R
Fixes #311. Feedback welcome. This is my first time writing methods for S3 classes.
> adding flatten argument for xml_find_all

- NEWS.md
- src/xml2_xpath.cpp
- tests/testthat/test-xml_find.R
Ran into this when making an interactive typo:
```
Error in xml_find_all.xml_node(., pg, "//div[contains(text(), 'Results')]") : 
STRING_ELT() can only be applied to a 'character vector', not a 'list'
```
The `STRING_ELT` part is likely to be puzzling, so we catch this mistake one line earlier instead.
> add a type check to xpath_search

- NEWS.md
- inst/include/xml2_types.h
We ran into a segfault, apparently due to double-deletion on destruction of an XPtr (unfortunately I couldn't trace down a good repro of this).
Defining the copy constructor and assignment operator explicitly as here (see also: https://stackoverflow.com/a/4172724/3576984) solved the issue.
> Add copy constructor and assignment operator for XPtr

- src/connection.cpp
std::back_inserter is used on L38:
https://en.cppreference.com/w/cpp/iterator/back_insert_iterator
> Add <iterator> include

- R/xml_text.R
- man/xml_text.Rd
One `xml_text` example includes the following comment:
```
#' # xml_double() and xml_integer() are useful for extracting numeric attributes
```
However, this text was previously spread across two lines:
```
#' # xml_double() and xml_integer() are useful for extracting numeric 
#' attributes
```
with the second line missing the # in front of it. When these examples are run (i.e. [in the reference docs](https://xml2.r-lib.org/reference/xml_text.html)), this extra text is treated as R code and run. Because `attributes` is an R function, the output is not what's intended:
```
attributes
#> function (x)  .Primitive("attributes")
```
This PR fixes this minor issue by simply moving the hanging word to the line above, which gives it a line length of exactly 80. An alternative solution if lines …
> One `xml_text` example wasn't properly escaped

- NEWS.md
- R/classes.R
- R/xml_modify.R
This gives a small performance improvement, e.g. for `xml_find_all(flatten = TRUE)`
``` r
library(xml2)
path <- xml2_example("cd_catalog.xml")
xml <- read_xml(path)
cds <- xml_find_all(xml, "CD")
find <- function() {
xml_find_all(cds, "TITLE", flatten = FALSE)
}
bench::mark(
find()
)
#> # A tibble: 1 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 find()        400µs    428µs     2165.    30.3KB     10.3
#> # A tibble: 1 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 find()        324µs    360µs     2529.    30.3KB     8.20
```
<sup>Created on 2023-06-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
This …
> Replace `structure()` by `class()`

- src/init.c
Our tooling flagged this inclusion as unused, and looking around I think everything needed is pulled from <Rinternals.h> (`SEXP`) and <R_ext/Rdynload.h> (`R_CallMethodDef`, `DL_FUNC`, `R_registerRoutines`, `R_useDynamicSymbols`) so that seems correct.
> Remove unused header

- NEWS.md
- R/xml_nodeset.R
- tests/testthat/_snaps/xml_nodeset.md
- tests/testthat/test-xml_nodeset.R
Closes #366.
There are some existing tests that were broken in as I was working on this, so I think those plus the new test are enough.
---
Re: the example raised in the issue, I see timing drop from ~1s to ~0.25s on my machine. Still noticeably slow, but a definite improvement. A quick profile shows we're going to need to drop to C++ to do any better.
> double-truncate to avoid inefficient encodeString() usage

- R/xml_parse.R
- man/read_xml.Rd
This package cannot be cross compiled, because it tries to evaluate something at install time. Therefore p3m and webr and r-universe need to patch this package, which is a headache, e.g https://github.com/r-wasm/xml2/tree/webr
This PR changes it such that this code is evaluated during CMD build, instead of CMD INSTALL, such that we can cross compile from a source package without having to run anything.
@georgestagg @tylfin
> Fix cross compilation issue

- R/as_xml_document.R
- R/paths.R
- R/utils.R
- R/xml_missing.R
- R/xml_serialize.R
- R/xml_write.R
- tests/testthat/_snaps/xml_parse.md
- tests/testthat/test-xml_parse.R
Fix #411 
I also added full stops to error messages.
I enhanced the `parse_options()` message to use `{.val`, so it now uses `"` instead of `'`. I added a `error_call` argument. to get better error messages. (See snapshot.) + a link to [`read_html()` docs](https://xml2.r-lib.org/reference/read_xml.html#arguments) where the options are all documented.
> Use cli messaging

- tests/testthat/_snaps/xml_attr.md
- tests/testthat/_snaps/xml_children.md
- tests/testthat/_snaps/xml_find.md
- tests/testthat/_snaps/xml_name.md
- tests/testthat/_snaps/xml_parse.md
- tests/testthat/_snaps/xml_write.md
- tests/testthat/test-xml_attr.R
- tests/testthat/test-xml_children.R
- tests/testthat/test-xml_find.R
- tests/testthat/test-xml_name.R
- tests/testthat/test-xml_parse.R
- tests/testthat/test-xml_write.R
> Use `expect_snapshot(error = TRUE)` over `expect_snapshot_error()`
